#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDDataGridWPF
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="N295_data")]
	public partial class VenusDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertFamilia(Familia instance);
    partial void UpdateFamilia(Familia instance);
    partial void DeleteFamilia(Familia instance);
    #endregion
		
		public VenusDbDataContext() : 
				base(global::CRUDDataGridWPF.Properties.Settings.Default.N295_dataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VenusDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VenusDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VenusDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VenusDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Familia> Familia
		{
			get
			{
				return this.GetTable<Familia>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="imp.pl_familias")]
	public partial class Familia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _xdescripcion;
		
		private string _xempresa_id;
		
		private string _xfamilia_id;
		
		private System.Nullable<decimal> _xporc_desc;
		
		private System.Nullable<decimal> _n295_porc_obs;
		
		private string _xnomen_comb;
		
		private System.Nullable<decimal> _xfactor_usupl;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnxdescripcionChanging(string value);
    partial void OnxdescripcionChanged();
    partial void Onxempresa_idChanging(string value);
    partial void Onxempresa_idChanged();
    partial void Onxfamilia_idChanging(string value);
    partial void Onxfamilia_idChanged();
    partial void Onxporc_descChanging(System.Nullable<decimal> value);
    partial void Onxporc_descChanged();
    partial void Onn295_porc_obsChanging(System.Nullable<decimal> value);
    partial void Onn295_porc_obsChanged();
    partial void Onxnomen_combChanging(string value);
    partial void Onxnomen_combChanged();
    partial void Onxfactor_usuplChanging(System.Nullable<decimal> value);
    partial void Onxfactor_usuplChanged();
    #endregion
		
		public Familia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xdescripcion", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string xdescripcion
		{
			get
			{
				return this._xdescripcion;
			}
			set
			{
				if ((this._xdescripcion != value))
				{
					this.OnxdescripcionChanging(value);
					this.SendPropertyChanging();
					this._xdescripcion = value;
					this.SendPropertyChanged("xdescripcion");
					this.OnxdescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xempresa_id", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string xempresa_id
		{
			get
			{
				return this._xempresa_id;
			}
			set
			{
				if ((this._xempresa_id != value))
				{
					this.Onxempresa_idChanging(value);
					this.SendPropertyChanging();
					this._xempresa_id = value;
					this.SendPropertyChanged("xempresa_id");
					this.Onxempresa_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xfamilia_id", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string xfamilia_id
		{
			get
			{
				return this._xfamilia_id;
			}
			set
			{
				if ((this._xfamilia_id != value))
				{
					this.Onxfamilia_idChanging(value);
					this.SendPropertyChanging();
					this._xfamilia_id = value;
					this.SendPropertyChanged("xfamilia_id");
					this.Onxfamilia_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xporc_desc", DbType="Decimal(19,4)")]
		public System.Nullable<decimal> xporc_desc
		{
			get
			{
				return this._xporc_desc;
			}
			set
			{
				if ((this._xporc_desc != value))
				{
					this.Onxporc_descChanging(value);
					this.SendPropertyChanging();
					this._xporc_desc = value;
					this.SendPropertyChanged("xporc_desc");
					this.Onxporc_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_n295_porc_obs", DbType="Decimal(19,4)")]
		public System.Nullable<decimal> n295_porc_obs
		{
			get
			{
				return this._n295_porc_obs;
			}
			set
			{
				if ((this._n295_porc_obs != value))
				{
					this.Onn295_porc_obsChanging(value);
					this.SendPropertyChanging();
					this._n295_porc_obs = value;
					this.SendPropertyChanged("n295_porc_obs");
					this.Onn295_porc_obsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xnomen_comb", DbType="VarChar(8)")]
		public string xnomen_comb
		{
			get
			{
				return this._xnomen_comb;
			}
			set
			{
				if ((this._xnomen_comb != value))
				{
					this.Onxnomen_combChanging(value);
					this.SendPropertyChanging();
					this._xnomen_comb = value;
					this.SendPropertyChanged("xnomen_comb");
					this.Onxnomen_combChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xfactor_usupl", DbType="Decimal(19,4)")]
		public System.Nullable<decimal> xfactor_usupl
		{
			get
			{
				return this._xfactor_usupl;
			}
			set
			{
				if ((this._xfactor_usupl != value))
				{
					this.Onxfactor_usuplChanging(value);
					this.SendPropertyChanging();
					this._xfactor_usupl = value;
					this.SendPropertyChanged("xfactor_usupl");
					this.Onxfactor_usuplChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
